version: '3'

services:

  node1:
    image: cassandra
    ports:
      - "9042:9042"
      - "9160:9160"
    environment:
      CASSANDRA_CLUSTER_NAME: demo
      CASSANDRA_SEEDS: node1, node2, node3
    restart: unless-stopped

  node2:
    image: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: demo
      CASSANDRA_SEEDS: node1, node2, node3
    restart: unless-stopped

  node3:
    image: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: demo
      CASSANDRA_SEEDS: node1, node2, node3
    restart: unless-stopped